import * as Notifications from 'expo-notifications';
import { Platform } from 'react-native';

import type { Profile } from '../data/types';
import { composeNotification, type NotifKind, type NotifState } from './copy';

/**
 * Local notifications for Phase 4 retention (US-13, US-14).
 *
 * Everything here is device-local (no push server) — scheduled reminders within
 * the user's chosen window, a "haven't logged in a while" nudge, an evening
 * streak-saver, and a goal-met celebration. The reminder schedule is driven by
 * the persisted Profile fields (`reminders_*`), so `syncReminders(profile)` is
 * the single source of truth: call it whenever those settings change.
 *
 * Copy is generated by `./copy` (the bratty-kid persona). Since local
 * notifications freeze their copy at schedule time, the callers pass a
 * best-effort `NotifState` snapshot (today's remaining ml + current streak) and
 * re-sync on app foreground / after each log to keep it reasonably fresh.
 *
 * We tag our notifications via `content.data.kind` so we can cancel just our own
 * without clobbering anything else.
 */

export type { NotifState } from './copy';

/** How long without a log before the nudge fires (hours). */
const INACTIVITY_HOURS = 5;

/** When the evening streak-saver fires (local hour). Late enough to be a real
 *  "last chance," independent of the reminder window. */
const STREAK_DANGER_HOUR = 21;

/**
 * Per-kind delivery config. On Android the sound is a property of the channel
 * (not the notification), so each kind gets its own channel; on iOS the sound
 * is set per-notification via `content.sound`. Custom sounds (`drop`/`nag`) are
 * bundled by the expo-notifications config plugin (see app.json) and take effect
 * after a fresh dev-client build — until then the OS falls back to the default
 * sound gracefully (no crash).
 */
const KIND_CONFIG: Record<
  NotifKind,
  { channelId: string; channelName: string; importance: number; androidSound: string; iosSound: string }
> = {
  reminder: {
    channelId: 'reminders',
    channelName: 'Hydration reminders',
    importance: Notifications.AndroidImportance.DEFAULT,
    androidSound: 'uongnuocdinao',
    iosSound: 'uongnuocdinao.wav',
  },
  nudge: {
    channelId: 'nudges',
    channelName: 'Gentle nudges',
    importance: Notifications.AndroidImportance.DEFAULT,
    androidSound: 'uongnuocdinao',
    iosSound: 'uongnuocdinao.wav',
  },
  streak_danger: {
    channelId: 'streak-danger',
    channelName: 'Streak alerts',
    importance: Notifications.AndroidImportance.HIGH,
    androidSound: 'nag',
    iosSound: 'nag.wav',
  },
  celebration: {
    channelId: 'celebrations',
    channelName: 'Celebrations',
    importance: Notifications.AndroidImportance.DEFAULT,
    androidSound: 'drop',
    iosSound: 'drop.wav',
  },
};

/**
 * Foreground handler — without this, notifications never present while the app
 * is open. SDK 56 uses `shouldShowBanner`/`shouldShowList` (the old
 * `shouldShowAlert` is deprecated). Sound is on so the persona's plip/nag lands.
 * Safe to call once at startup.
 */
export function configureNotificationHandler(): void {
  Notifications.setNotificationHandler({
    handleNotification: async () => ({
      shouldShowBanner: true,
      shouldShowList: true,
      shouldPlaySound: true,
      shouldSetBadge: false,
    }),
  });
}

/** Ask the OS for permission, registering our per-kind Android channels. */
export async function requestPermissions(): Promise<boolean> {
  if (Platform.OS === 'android') {
    await Promise.all(
      Object.values(KIND_CONFIG).map((c) =>
        Notifications.setNotificationChannelAsync(c.channelId, {
          name: c.channelName,
          importance: c.importance,
          sound: c.androidSound,
        }),
      ),
    );
  }
  const existing = await Notifications.getPermissionsAsync();
  if (existing.granted) return true;
  const requested = await Notifications.requestPermissionsAsync({
    ios: { allowAlert: true, allowBadge: true, allowSound: true },
  });
  return requested.granted;
}

/** Cancel only the scheduled notifications we tagged with one of `kinds`. */
async function cancelKinds(...kinds: NotifKind[]): Promise<void> {
  const scheduled = await Notifications.getAllScheduledNotificationsAsync();
  await Promise.all(
    scheduled
      .filter((n) => kinds.includes(n.content.data?.kind as NotifKind))
      .map((n) => Notifications.cancelScheduledNotificationAsync(n.identifier)),
  );
}

/** The reminder slots (local hours) implied by the window + interval. */
function reminderHours(profile: Profile): number[] {
  const { reminder_window_start_hour: start, reminder_window_end_hour: end } = profile;
  const step = Math.max(1, profile.reminder_interval_hours);
  const hours: number[] = [];
  for (let h = start; h <= end; h += step) hours.push(h);
  return hours;
}

/** Build the platform-specific content bits for a composed notification. */
function contentFor(kind: NotifKind, title: string, body: string) {
  const cfg = KIND_CONFIG[kind];
  return {
    title,
    body,
    data: { kind } as { kind: NotifKind },
    sound: cfg.iosSound, // iOS only; ignored on Android (channel carries sound)
  };
}

/**
 * Reconcile the OS's scheduled reminders with the user's settings. Cancels the
 * previous schedule and re-creates it from the Profile — idempotent, so it's
 * safe to call on every profile change / app foreground. Each slot gets fresh,
 * varied persona copy (no repeats within the day). No-op when disabled.
 */
export async function syncReminders(profile: Profile, state: NotifState = {}): Promise<void> {
  await cancelKinds('reminder');
  if (!profile.reminders_enabled) return;

  const granted = await requestPermissions();
  if (!granted) return;

  const exclude = new Set<string>();
  await Promise.all(
    reminderHours(profile).map((hour) => {
      const { title, body } = composeNotification('reminder', profile, state, { hour, exclude });
      return Notifications.scheduleNotificationAsync({
        content: contentFor('reminder', title, body),
        trigger: {
          type: Notifications.SchedulableTriggerInputTypes.DAILY,
          hour,
          minute: 0,
          channelId: KIND_CONFIG.reminder.channelId,
        },
      });
    }),
  );
}

/**
 * (Re)arm the "haven't logged in a while" nudge. Call after each successful log
 * to push it back out, and on app open. A one-shot timer `INACTIVITY_HOURS` out.
 * No-op when reminders are off.
 */
export async function bumpInactivityNudge(profile: Profile, state: NotifState = {}): Promise<void> {
  await cancelKinds('nudge');
  if (!profile.reminders_enabled) return;
  const granted = await requestPermissions();
  if (!granted) return;

  const { title, body } = composeNotification('nudge', profile, state);
  await Notifications.scheduleNotificationAsync({
    content: contentFor('nudge', title, body),
    trigger: {
      type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,
      seconds: INACTIVITY_HOURS * 3600,
      repeats: false,
      channelId: KIND_CONFIG.nudge.channelId,
    },
  });
}

/**
 * Evening streak-saver (the retention lever). Fires at `STREAK_DANGER_HOUR` only
 * when there's a live streak to lose *and* today's goal isn't met yet. Cancels
 * itself once the goal is met (remaining <= 0) — so re-syncing on foreground /
 * after a log that crosses the goal silences it. Frozen-copy caveat applies:
 * the streak number reflects the last snapshot, refreshed on each re-sync.
 */
export async function syncStreakDanger(profile: Profile, state: NotifState = {}): Promise<void> {
  await cancelKinds('streak_danger');
  if (!profile.reminders_enabled) return;
  const hasStreak = (state.streak ?? 0) > 0;
  const goalMet = state.remaining_ml != null && state.remaining_ml <= 0;
  if (!hasStreak || goalMet) return;

  const granted = await requestPermissions();
  if (!granted) return;

  const { title, body } = composeNotification('streak_danger', profile, state, {
    hour: STREAK_DANGER_HOUR,
  });
  await Notifications.scheduleNotificationAsync({
    content: contentFor('streak_danger', title, body),
    trigger: {
      type: Notifications.SchedulableTriggerInputTypes.DAILY,
      hour: STREAK_DANGER_HOUR,
      minute: 0,
      channelId: KIND_CONFIG.streak_danger.channelId,
    },
  });
}

/**
 * Fire a one-off celebration when the daily goal is reached. The richer
 * celebration is in-app (Home); this is the out-of-app pat on the back, in the
 * persona's grudgingly-proud voice. Best effort — silently ignored if
 * permission isn't granted.
 */
export async function celebrateGoalMet(
  profile: Profile | null = null,
  state: NotifState = {},
): Promise<void> {
  const { granted } = await Notifications.getPermissionsAsync();
  if (!granted) return;
  const { title, body } = composeNotification('celebration', profile, state);
  await Notifications.scheduleNotificationAsync({
    content: contentFor('celebration', title, body),
    trigger: null, // present immediately
  });
}

/** Cancel everything we scheduled — used on data/account deletion. */
export async function cancelAllReminders(): Promise<void> {
  await cancelKinds('reminder', 'nudge', 'streak_danger');
}
